### ISSUE TITLE
support `u8` string literals

### ISSUE THREAD

**Issue by zamfofex** [tyfkda/xcc#108]
Prefixing a string literal with `u8` makes it be certainly encoded as UTF‐8 at runtime, even in implementations where the runtime encoding isn’t UTF‐8. In implementations where the encoding is indeed already UTF‐8, this ought to be (mostly) ignored.

As of C23, in implementations with UTF‐8 as the runtime encoding, the only difference between `"hello"` and `u8"hello"` is that the former is an expression of type `char *`, whereas the latter is an expression of type `unsigned char *`.

**Comment by tyfkda** [comment]
Thank you to suggest C language features.

I'm afraid, but I don't have any plan to support string encoding any time soon.
So I worry about enabling `u8` string literal makes users confusing.

**Comment by zamfofex** [comment]
I understand. That feels unfortunate to me, because `u8` literals are the only way to ensure a string is encoded as ASCII/UTF‐8 at runtime across different comforming implementations. (And I would like for my program to work portably across any such implementation.) But I suppose nowadays non‐ASCII implementations are uncommon enough that this is only a theoretical problem.
