### ISSUE TITLE
goto

### ISSUE THREAD

**Issue by tyfkda** [tyfkda/xcc#14]

**Comment by GitMensch** [comment]
Can you please elaborate? README.md has this as missing feature.

**Comment by tyfkda** [comment]
@GitMensch Yes, `goto` is not supported in WebAssembly.
You can create a new issue.
But so far I can't think of a good idea to support `goto` in WASM architecture.

Currently, AST is used instead of IR to compile C sources to wasm binaries.
AST preserves the C syntax tree structure and matches the wasm architecture.
So basically no conversion is processed.

To support `goto`, I think it'll need to convert from IR to wasm or some other code conversion.

Might be able to support computed gotos outside the wasm platform
(and I think it's even harder with wasm),
So I prefer to split the problem.
