### ISSUE TITLE
Which license is used for XCC

### ISSUE THREAD

**Issue by ijsf** [tyfkda/xcc#152]
First of all, thanks for this project. For my particular WASM use case, I've been looking for something between the lightning fast but outdated [TCC](https://bellard.org/tcc/) and the unbearingly slow but solid [LLVM](https://github.com/llvm/llvm-project). XCC seems to meet most requirements and is super fast!

I couldn't find a LICENSE file in the repository or in the repository details though. I just wanted to clarify under which OSS license this project is released.

The `package.json` file seems to mention MIT:
https://github.com/tyfkda/xcc/blob/bdddc1c75e0026887e037454fda23dcac7d67208/package.json#L24

Does this mean the entire codebase is MIT licensed?

**Comment by tyfkda** [comment]
@ijsf Thank you for your interest in my project.
I forgot to specify the license until now.
I have added the MIT license file, so please take a look.

**Comment by ijsf** [comment]
Excellent, thanks!
