### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by chatchoi** [tyfkda/xcc#172]
Just another ELF64 platform.

**Comment by tyfkda** [comment]
I don't have FreeBSD environment, so I cannot test on it.
Would you tell me major differences/problems?

**Comment by mingodad** [comment]
Just for you to know that FreeBSD and OpenBSD can be installed in VirtualBox or similar.

**Comment by tyfkda** [comment]
I'm sorry but I don't have strong motivation to support the platform.
