### ISSUE TITLE
Export (`-e` option) Issue

### ISSUE THREAD

**Issue by jeff-hykin** [tyfkda/xcc#177]
Here's a minimal reproduction for `-e` not exporting when outputting an object file (`-c`).
Maybe that is intended behavior, but it would be nice to avoid needing a main function (and the wasi imports that are needed for a main function).

```js
// import DisWasm, WccRunner

const wccRunner = new WccRunner()
await wccRunner.setup()
await wccRunner.writeFile("main.c" `
int fib(int n) {
    if (n < 2)
        return n;
    else
        return fib(n - 1) + fib(n - 2);
}
`)
const exitCode = await wccRunner.compile("main.c", [ "--verbose", "-e", "fib", "-c", "-o", "main.o", "--import-module-name=env", ])
if (exitCode !== 0) {
    throw new Error(`Compile failed: ${exitCode}`)
}

// display wasm output
const disWasm = new DisWasm((await wccRunner.readFile("main.o")).buffer)
let compiledWasm = ""
disWasm.setLogFunc((code)=>compiledWasm+=(code+"\n"))
disWasm.dump()
console.log(`compiledWasm is:`,compiledWasm)
```

- Note 1 (wccfiles.zip): I tried this using both the [wccfiles.zip](https://tyfkda.github.io/xcc/wccfiles.zip) from the website, and one I compiled. Both have the issue.
- Note 2: The one I compiled prints out `-e optarg is: fib`, so it seems to be getting the argument at least
- Note 3: The cli works (`./wcc -e fib -o fib.wasm examples/my_fib.c` outputs a .wasm with `(export "fib" (func 7))`)

Here's the compiler verbose output:

```
### Exports

fib



### Globals(import)

 0: __stack_pointer (1)

### Globals(data)

### Globals(bss)

### Functions

 0: fib



### Memory  0x1

---- BSS  0x1
```

Here's what that example compiles to:
```wasm
(module
;; WASM version: 1

;;=== 0x8: TYPE, len=6
(type (func (param i32) (result i32)))  ;; 0

;;=== 0x10: IMPORT, len=47
(import "env" "__linear_memory" (memory 0 (;index=0;)))
(import "env" "__stack_pointer" (global (mut i32)))  ;; 0

;;=== 0x41: FUNC, len=2
;; func: #1
;;   func 0: type=#0

;;=== 0x45: CODE, len=38
(func $fib (;0;) (type 0)
  local.get 0
  i32.const 2
  i32.lt_s
  if (result i32)
    local.get 0
  else
    local.get 0
    i32.const 1
    i32.sub
    call $fib
    local.get 0
    i32.const 2
    i32.sub
    call $fib
    i32.add
  end
)
```

**Comment by tyfkda** [comment]
@jeff-hykin I'm not sure this works for you, but
would you try with the option `--entry-point=` to suppress entry point, please?

**Comment by jeff-hykin** [comment]
Sure! I'll try that later today probably.

Also thank you for this incredible library! I have been waiting 5 years for this (ever since Ben Smith's llvm-in-the-browser demo at cpp con 2019). I can't believe you got it working targeting wasm, x86-64, aarch64 (arm64), AND riscv64.

I got xcc working with Deno last week. It required a number of hacks, so I've been cleaning those up the last few days.

**Comment by jeff-hykin** [comment]
Update: `--entry-point=` worked! Thanks!
