### ISSUE TITLE
Function named `__main_argc_argv`

### ISSUE THREAD

**Issue by jeff-hykin** [tyfkda/xcc#181]
I know, I know, unlikely, but I was running xcc on some test cases and got a compile error for this:

```c
int __main_argc_argv() {
  return 1;
}
int main() {
  return 0;
}
```

Error:
```
src/cc/frontend/var.c:54: define_global: Assertion `storage & VS_EXTERN` failed
```

I confirmed gcc and clang can compile this.

**Comment by tyfkda** [comment]
@jeff-hykin 
The reason is that `wcc` renames the `main` function to `__main_argc_argv`, which causes a definition conflict.
At least it is bad that `assert` is generated, so I modified it to raise an error.

**Comment by jeff-hykin** [comment]
Why does it need to rename main?

**Comment by tyfkda** [comment]
The reason for renaming the main function is to make the wcc output compilable and linkable in Emscripten as well.

```sh
$ ./wcc -c examples/hello.c && emcc -o hello.wasm hello.o && ./tool/runwasi hello.wasm
Hello, world!
```

**Comment by jeff-hykin** [comment]
Oh. So is the rename specific to targeting webassembly?

I'm guessing emscripten expects `__main_argc_argv` to be exported for main functions that take arguments (e.g. `int main(int argc, char* argv)`) and then uses something else like `__main` for `int main()`.

**Comment by tyfkda** [comment]
I'm going to close this issue.
