### ISSUE TITLE
support global base ?

### ISSUE THREAD

**Issue by pmp-p** [tyfkda/xcc#185]
same as linker option `--global-base=` from https://lld.llvm.org/WebAssembly.html
which allows to make a fixed gap from addr 1 to whatever before data

**Comment by tyfkda** [comment]
@pmp-p How do you envision using it?

**Comment by pmp-p** [comment]
As it is a linker argument i guess the standard would be `-Wl,--global-base=` on compiler command line

if you are wondering why making such gap, it is for use without any stdlib for compute only + ringbuffers, or a convenient place to put some [I/O buffers](https://wiki.osdev.org/Memory_Map_(x86))

**Comment by tyfkda** [comment]
Since the stack area is currently allocated at the top of linear memory in wcc, the same can be achieved by specifying the stack size.
Could you try the `--stack-size` option?

```sh
$ ./wcc --stack-size=65536 examples/hello.c
$ npx ts-node tool/diswasm.ts a.wasm
...
;;=== 0x1e0c: DATA, len=328
(data (;0;) (i32.const 65537) "Hello, world!\0a")
...
```

**Comment by tyfkda** [comment]
I am going to close this issue.
