### ISSUE TITLE
Support variable length array

### ISSUE THREAD

**Issue by tyfkda** [tyfkda/xcc#65]
- [x] allocate
- [x] typedef
- [x] sizeof
- [x] multiple dimension
- [ ] function parameter
- [ ] rewind in loop

**Comment by zamfofex** [comment]
Can’t this issue be closed now?

**Comment by tyfkda** [comment]
Thank you for pointing this out.
There are still some tricky cases left, but the basic functionality should be working, so I've changed my mind to close this issue.
